# Change these first
owner: asdofindia # Your GitHub organization or username, where this repository lives
repo: services-uptime # The name of this repository

sites:
  - name: ASD
    url: https://asd.learnlearn.in
  - name: Learn Learnin'
    url: https://learnlearn.in
  - name: Daktre
    url: https://daktre.com
  - name: Doddasampige
    url: https://doddasampige.daktre.com
  - name: Kaanu
    url: https://kaanu.daktre.com
  - name: Tobacco Questions
    url: https://tobaccoquestions.iphindia.org/api/dimensionValues/ministry
  - name: Tobacco Data
    url: https://tobaccodata.iphindia.org
  - name: Tribal Health Initiative
    url: https://tribalhealth.org
  - name: Mail
    url: https://mail.free.gen.in/sso/login?url=/webmail/?homepage
  - name: Akshay's ActivityPub
    url: https://social.learnlearn.in
  - name: SAA Karnataka
    url: https://saakarnataka.org
  - name: Arunodaya Trust
    url: https://arunodayatrust.in
  - name: MathsFunda
    url: https://mathsfunda.com

assignees:
  - asdofindia
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /services-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "The status monitor for some of the services deployed by Akshay"
  introMessage: If you like to contact Akshay for any reason, you can [find the contact details here](https://asd.learnlearn.in/about#contact)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
